Settings:
  "vault-hook": true
  "database-type": "file"
Databases:
  MongoDB:
    "connection-uri": "mongodb://localhost:27017"
    "database-name": "Stark"
  MySQL:
    "host": "localhost"
    "port": 3306
    "username": "root"
    "password": "password"
    "database": "Stark"
  Titanium:
    "host": "localhost"
    "port": 2048
    "username": "admin"
    "password": "password"
    "database": "Stark"
Messages:
  "account_created": "&a&lSUCCESS! &aYour account has been created successfully."
  "account_not_found": "&c&lERROR! &cNo account found for &6%player%"
  "account_deleted": "&c&lNOTICE! &cYour account has been deleted."
  "view-balance-self": "&eYour balance is &a$%balance%"
  "view-balance-other": "&6%player%'s &ebalance is &a$%balance%"
  "balance_update": "&a&lUPDATE! &aYour new balance is &e$%balance%"
  "deposit_success": "&a&lSUCCESS! &aYou have successfully deposited &e$%amount% &ainto your account."
  "withdraw_success": "&a&lSUCCESS! &aYou have successfully withdrawn &e$%amount% &afrom your account."
  "deposit_failure": "&c&lERROR! &cDeposit failed. Please try again later."
  "withdraw_failure": "&c&lERROR! &cWithdrawal failed. Please try again later."
  "transaction_success": "&a&lSUCCESS! &aYou have successfully transferred &b$%amount% &ato &b%player%"
  "transaction_failure": "&c&lERROR! &cTransaction failed. Please try again later."
  "transaction_pending": "&e&lNOTICE! &eYour transaction is pending."
  "notice_player_paid_other": "&e&lNOTICE! &aYou have paid &b$%amount% &ato &b%player%"
  "notice_player_received_other": "&e&lNOTICE! &aYou have received &b$%amount% &afrom &b%player%"
  "error_no_permission": "&c&lERROR! &cI'm sorry, but it seems that you do not have permission to do this. If you believe this is an error, please contact an administrator immediately."
  "error_no_money": "&c&lERROR! &cYou do not have the funds to do this!"
  "insufficient_balance": "&c&lERROR! &cYou do not have enough balance to make this transaction."
  "invalid_amount": "&c&lERROR! &cThe amount you entered is invalid. Please enter a valid amount."
  "self_transaction_error": "&c&lERROR! &cYou cannot transfer money to yourself."
  "player_not_found": "&c&lERROR! &cThe player you are trying to transfer money to does not exist."
  "player-never-played": "&c&lERROR! &c%player% has never played before."


