Settings:
  "vault-hook": true
  "database-type": "file"
Databases:
  MongoDB:
    "connection-uri": "mongodb://localhost:27017"
    "database-name": "Stark"
  MySQL:
    "host": "localhost"
    "port": 3306
    "username": "root"
    "password": "password"
    "database": "Stark"
  Titanium:
    "host": "localhost"
    "port": 2048
    "username": "admin"
    "password": "password"
    "database": "Stark"
Messages:
  "player-never-played": "&c%player% has never played before."
  "view-balance-self": "&7[&6Stark&7] &fYour balance is: &e$%balance%"
  "view-balance-other": "&7[&6Stark&7] &fThe balance of &e%player% &fis: &e$%balance%"