mongodb:
  user: "admin"
  password: "admin"
  host: "localhost"
  url: "mongodb+srv://[username:password@]host[/[defaultauthdb][?options]]"


death-event:
  giveMoney: true
  minKillMoney: 100
  maxKillMoney: 1000
